resources:
- name: concourse-demo-acceptance-tests
  type: git
  source: {uri: "https://github.com/ONSdigital/concourse-demo-acceptance-tests"}

jobs:
- name: acceptance-tests
  serial_groups: [acceptance_tests]
  plan:
  - get: concourse-demo-acceptance-tests
    trigger: true
  - task: run-acceptance-testsf
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: kennethreitz/pipenv
      inputs:
        - name: concourse-demo-acceptance-tests
      params:
        ENDPOINT: 'http://concourse-demo-python.apps.devtest.onsclofo.uk'
      run:
        path: sh
        dir: concourse-demo-acceptance-tests
        args:
        - -exc
        - |
          pipenv install
          pipenv run behave