resources:
- name: concourse-demo-acceptance-tests
  type: git
  source: {uri: "https://github.com/ONSdigital/concourse-demo-acceptance-tests"}

jobs:
- name: hello
  plan:
  - get: concourse-demo-acceptance-tests
    trigger: true
  - task: helloworld
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      run:
        path: sh
        args:
        - -exc
        - |
          echo helloworld